services:
  postgres-nodejs:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=nodejsdb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=username'
    ports:
      - '5432:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'

  pgadmin-nodejs:
    image: dpage/pgadmin4
    container_name: pgadmin4_nodejs
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@acdevs.pt
      PGADMIN_DEFAULT_PASSWORD: changemeinproduction
    volumes:
      - 'pgadmin-data:/var/lib/pgadmin'

volumes:
  db:
  pgadmin-data: